# Create image based on the official Node 10 image from dockerhub
FROM node:14

# Create a directory where our app will be placed
RUN mkdir -p /app/client

# Change directory so that our commands run inside this new directory
WORKDIR /app/client

# Copy dependency definitions
COPY package.json /app/client/

# Install dependecies
RUN npm install

# Get all the code needed to run the app
COPY . .

# Expose the port the app runs in
EXPOSE 4200 49153

# Serve the app
CMD ["npm", "start"]
