export enum VideoType {
    TYPE_YOUTUBE = 'TYPE_YOUTUBE',
    TYPE_FACEBOOK = 'TYPE_FACEBOOK',
    TYPE_URL = 'TYPE_URL',
    TYPE_VIDEO = 'TYPE_VIDEO'
}



export enum ContentType {
    IMAGE = 'IMAGE',
    IMAGE_GOOGLE =  'IMAGE_GOOGLE',
    IMAGE_FACEBOOK = 'IMAGE_FACEBOOK',
    IMAGE_TWITTER =  'IMAGE_TWITTER',
    IMAGE_INSTAGRAM = 'IMAGE_INSTAGRAM',
    IMAGE_SNAPSHOT = 'IMAGE_SNAPSHOT',
    IMAGE_RSS = 'IMAGE_RSS',
    VIDEO = 'VIDEO',
    VIDEO_YOUTUBE = 'VIDEO_YOUTUBE',
    VIDEO_FACEBOOK = 'VIDEO_FACEBOOK',
    VIDEO_TWITTER = 'VIDEO_TWITTER',
    VIDEO_INSTAGRAM = 'VIDEO_INSTAGRAM',
    TEXT= 'TEXT',
    TEXT_TWITTER = 'TEXT_TWITTER',
    TEXT_FACEBOOK = 'TEXT_FACEBOOK',
    TEXT_LINKEDIN = 'TEXT_LINKEDIN',
    TEXT_INSTAGRAM = 'TEXT_INSTAGRAM',
    TEXT_RSS = 'TEXT_RSS',
    TEXT_EXT = 'TEXT_EXT',
    LINK = 'LINK',
    THUMB = 'THUMB',
    TEXT_WALLIFY = 'TEXT_WALLIFY',
    RICH_TEXT = 'RICH_TEXT',
    POST_TWITTER = 'POST_TWITTER',
    POST_FACEBOOK = 'POST_FACEBOOK',
    NOTE = 'NOTE',
    MULTIPLE = 'MULTIPLE',
    MULTIPLE_FACEBOOK = 'MULTIPLE_FACEBOOK',
    MULTIPLE_TWITTER = 'MULTIPLE_TWITTER',
    MULTIPLE_LINKEDIN = 'MULTIPLE_LINKEDIN',
    MULTIPLE_INSTAGRAM = 'MULTIPLE_INSTAGRAM',
    LOCATION = 'LOCATION',
    COMMENT = 'COMMENT',
    LIKE = 'LIKE',
    DEEPLINK = 'DEEPLINK'
}
