sudio: required
services: 
    - docker
      
script:
    - docker build -t basvanpol/fs-client ./client
    - docker build -t basvanpol/fs-server ./server
    # login to docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # push these images to docker hub
    - docker tag basvanpol/fs-client:latest
    - docker tag basvanpol/fs-server:latest
    - docker push basvanpol/fs-client:latest
    - docker push basvanpol/fs-server:latest

deploy:
    edge: true
    provider: elasticbeanstalk
    region: ap-southeast-2
    app: Flowstream
    env: Flowstream-env
    bucket_name: elasticbeanstalk-ap-southeast-2-747446493647
    bucket_path: Flowstream
    on: 
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
