version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  client: # name of the first service
    build: 
        context: ./client # specify the directory of the Dockerfile
        dockerfile: Dockerfile
    ports:
      - "4200:4200" # specify port forewarding
      - "8080:8080" # specify port forewarding
    links:
        - server

  server: #name of the second service
    build: 
        context: ./server # specify the directory of the Dockerfile
        dockerfile: Dockerfile
    ports:
      - "8090:8090" #specify ports forewarding