version: "3" # specify docker-compose version

# Define the services/containers to be run
services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
      - client
      - content-server

  client: # name of the first service
    build:
      context: ./client # specify the directory of the Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  api: #name of the second service
    build:
      context: ./api # specify the directory of the Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
  content-server: #name of the second service
    build:
      context: ./content-server # specify the directory of the Dockerfile
      dockerfile: Dockerfile
